import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

// Configuración de las fuentes locales
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadatos de la aplicación
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-background p-4 shadow-md">
          <nav>
            <ul className="flex justify-center space-x-8 text-lg font-medium">
              <li>
                <Link href="/authentication/login" className="hover:text-primary transition-colors">Login</Link>
              </li>
              <li>
                <Link href="/authentication/register" className="hover:text-primary transition-colors">Register</Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="min-h-screen bg-foreground py-8 px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
